server:
  port: 9001

eureka:
  instance:
#    prefer-ip-address: true
    hostname: locatest1
#    ip-address: 172.19.2.122
  client:
    # 向注册中心注册自己  单机开false
    # 检索服务 单机开false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
          defaultZone: http://locatest2:9002/eureka/
  server:
     enable-self-preservation : false
     eviction-interval-timer-in-ms : 30000