server:
  port: 9001

spring:
  application:
    name: uusmart-eureka

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
          defaultZone:http: http://172.19.2.121:9001/eureka/
    server:
      enable-self-preservation : false
      eviction-interval-timer-in-ms : 30000